services:
  db:
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: full_stack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  dimax-api:
    container_name: dimax-api
    image: stepashka37/dimax-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/full_stack
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  dimax-react:
    container_name: dimax-react
    image: stepashka37/dimax-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - dimax-api
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db: