name: CI - Build Backend

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: full_stack
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and run ITs with Maven
        run: mvn -ntp -B verify
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New pull request
          webhook: https://discord.com/api/webhooks/1201555095750463638/TaSVoCC9zEs3VUGdT8CuRO2gSabCyi_n2bsu1oE2-qJpbJAmFagC5-L4uBodJvt8QON4